bruin-tennis-consulting/match-manager

- components/SearchDropdown.js
- styles/SearchDropdown.module.css
Fixes #5 
- Added loading animation in dropdown while the content is being fetched.
- The code for fetching data as the site loads is already in place.
> Fix #5 : Added loading animation in Dropdown

- components/SearchDropdown.js
- replace function with inline arrow function
> refactor loading

- components/FilterList.js
1. Active filters will be highlighted blue in the available filter list.
2. Only 1 filter heading can be open at a time.
3. Clicking on a blue filter will deselect it.
> Improved filter list

- services/nameMap.js
Commented out Data Version 1, because new data is not in this format.
// Data Version 1
// "Name"                   : 'Point Score',
//  "Shot 1: gameScore"      : 'Game Score',
//  "Shot 1: setScore"       : 'Set Score',
//  "Shot 1: serverName"     : 'Server Name',
//  "Shot 1: firstServeIn"   : 'First Serve In',
//  "Shot 1: firstServeZone" : 'First Serve Zone',
//  "Shot 1: secondServeIn"  : 'Second Serve In',
//  "Shot 1: secondServeZone": 'Second Serve Zone',
//  "Shot 2: returnData"     : 'Return Data',
> NameMap.js Update (Commented out Old filters)

- .eslintrc.json
- app/(interactive)/layout.js
- app/(interactive)/matches/[slug]/page.js
- app/(interactive)/tag-match/page.js
- app/components/FilterList.js
- app/components/VideoPlayer.js
- app/layout.js
fix eslint errors that prevents npm build on GitHub Action to Firebase
> App router

- app/components/FilterList.js
- I gave Jerry some old code that didn't follow eslint rules which got merged in and fails the build. should be fixed
> fix eslint

- app/(interactive)/tag-match/page.js
- package-lock.json
Issue #33, where the spacebar now doesn't cause the edited timestamp to display NaN and lose it's value, also arrow keys are now functional outside of the video.
> fixed issues with the spacebar

- README.md
- app/(interactive)/matches/[slug]/page.js
- app/(interactive)/upload-video/page.js
- app/components/MatchTiles.js
- app/services/getLogos.js
- app/services/uploadMatch.js
- app/styles/MatchTiles.module.css
- app/styles/Upload.module.css
> Match info tiles + Logo Support (oops forgot to make a new branch for this)

- app/(interactive)/matches/[slug]/page.js
- app/components/SearchDropdown.js
- app/services/transformData.js
- when points[0].Position is integer 0, we incorrectly set the version to 1. instead, just check if it exists
- change dynamic url to document id so we can upload multiple matches of the same video id (debugging/partial tagged stuff)
> transformData bug and update dynamicURL

- app/(interactive)/upload-match/page.js
- app/(interactive)/upload-team/page.js
- app/services/upload.js
> Added new player format

- app/components/SearchDropdown.js
- looks messy but it's ok because it's a temp fix.
- when we move to the new data storage format, we can simply use the date field
> Chronological

- app/services/taggerButtonData.js
added (data) back into two lines, bc it was missing after "isexciting" commit
> added data back into line 322 and line 332

- app/services/taggerButtonData.js
fixed minor tagging bug - according to Leo
Jerry pull requests here
> added isPointEnd to double fault

- app/components/MatchTiles.js
- app/components/PointsList.js
- app/components/ScoreBoard.js
- app/styles/MatchTiles.module.css
- app/styles/PointsList.module.css
- app/styles/Scoreboard.module.css
Fixed scoreboard, matchtiles, and image formatting for Pointlist.
> Filter pointslist split

- app/(interactive)/tag-match/page.js
Added download CSV functionality, while keeping copy columns button as well.
> Added download CSV functionality

- app/(interactive)/matches/[slug]/page.js
- app/styles/Match.module.css
Fixed minor detailed point list redirection error
> Detailed pointlist krish fix

- app/(interactive)/matches/[slug]/page.js
- app/components/PointsList.js
- app/styles/Match.module.css
> bookmark functionality

- app/(interactive)/tag-match/page.js
- app/components/PointsList.js
addresses a few bugs:
1. download csv does not download Point Winner
2. regex parsing in pointsList fails to parse 40-A and A-40 pointScores. Instead I opted to directly use the property of point
> Swap player won

- app/components/SignIn.js
Firebase did not allow a password shorter than 6 characters. Secondly, the demo account seemed to have been removed over the summer so I created that again recently.
> Password hint was incorrect. 

- .vscode/settings.json
- app/components/SignIn.js
Added text to the sign in box that says the password is incorrect when the user unsuccessfully tries a login. Red and centered above the "sign in to your account" text.
> Incorrect password hint #201 resolved

- app/(interactive)/matches/[slug]/page.js
> 193-fixed-pdf-tab-styling

- app/(interactive)/match-list/page.js
- app/(interactive)/upload-match/page.js
- app/components/MatchDataProvider.js
- app/services/matchSchemas.js
hotfix for leo
- display match-list with unique id
- bugfix upload
> helpful match-list display; upload bug

- app/components/DashboardTile.js
- app/components/MatchTiles.js
- app/components/ScoreBoard.js
Fixed the bolding issue for Scoreboard ,Dashboard, and Match Tiles (Used same logic for Dashboard Tiles)
> Fixed the bolding issue for Scoreboard,Dashboard, and MatchTiles

- app/DataProvider.js
- app/components/Dashboard.js
- app/components/DashboardTile.js
- app/components/MatchTiles.js
- app/components/ScoreBoard.js
- app/matches/[slug]/page.js
- app/services/matchSchemas.js
- app/services/taggerButtonData.js
- app/tag-match/[slug]/page.js
- app/upload-match/page.js
- package-lock.json
- package.json
Added a jump to button that either takes milliseconds, or a combination of minutes and seconds. This allows taggers to jump to a certain time in the videoplayer.
> 231 timestamp shortcuts jump for tagging

- app/components/Dashboard.js
- app/components/DashboardTile.js
- app/components/ExtendedList.js
- app/components/MatchTiles.js
- app/components/PlayerProfileHeader.js
- app/components/PointsList.js
- app/components/RosterTile.js
- next.config.js
#284 Changed all img tags to Next.js Image component. Added alternate text and edited next.config.js to allow photos from Firebase backend.
> 284 img to image component.

- app/components/MatchTiles.js
- app/components/PlayerProfile.js
- app/profile/[playerId]/page.js
- app/services/matchSchemas.js
- app/services/upload.js
- app/tag-match/[slug]/page.js
- app/timestamp-tagger/page.js
- app/upload-match/page.js
- app/upload-team/page.js
Add new coordinate system, similar to the full tagger. Attached a picture of the change in issue #303
> Changed coordinate system

- app/components/FilterList.js
- app/components/MatchTiles.js
- app/components/PlayerProfile.js
- app/profile/[playerId]/page.js
- app/services/matchSchemas.js
- app/services/upload.js
- app/upload-match/page.js
- app/upload-team/page.js
- The scaling has been fixed by viewport mapping and this seems to have fixed most of the problems. 
- The jumping to the top problem seems to be a re-rendering issue every time you select a filter. A potential fix has been implemented in this PR by adding a button for "apply filters" which will allow for better User Experience by removing the jump. However, it does add a button that you need to click. 
- The IOS problem seems to be related to the character that is being used. Implemented a IOS friendly unicode character for now.
> Potential fix for filter list styling. 

- app/services/matchSchemas.js
- app/upload-match/page.js
Added a progress bar to the top of the component, however I haven't tested with actual Json data yet, which could have caused the initial issue with the upload. 
Made the progress bar styling more efficient with useMemo, added a check so we don’t update player options if clientTeam is missing, cleaned up how team and player data get parsed to avoid doing it repeatedly, used functional state updates for smoother transitions, and made sure the progress timer gets properly cleaned up.
> 310 uploading not working

- app/upload-team/page.js
In team upload page now, if team already exists will throw an error message
> 328 Unique Teams

- app/components/Dashboard.js
closes #323 
Event dates were labeled as Invalid Date. Changed this using parsing logic to have a range of dates through all the matches in the event.
> Event Dates Range

- app/components/FilterList.js
- app/components/MatchTiles.js
- app/matches/[slug]/page.js
- app/styles/Match.module.css
- app/styles/Scoreboard.module.css
made chagnes in #325 , 
**move live score below active filters and change button colors to sign up**
**updated date**
**swapped colors**
**remaining issues:**
- For match details, I have date, but looking at fire base, there doesn't seem to be any other value that's consistent and meaningful, so I have it sent to event if not null, else if venue if its not null, else nothing like in the sc
> #325 Match Viewer Page Quality of Life

- app/styles/Upload.module.css
- app/upload-match/page.js
> Added a green success bar indicating that the match has been uploaded successfully

- app/components/VideoPlayer.js
- app/match-list/page.js
- app/services/downloadCollectionAsZip.js
- app/styles/MatchList.css
- app/styles/VideoPlayer.module.css
- package-lock.json
- package.json
Closes #342. 
Added styles for the `VideoPlayer` component which maintains the correct dimensions for the video on mobile when going from vertical to horizontal (and vice versa)
> 342 bug mobile embedded yt dimension

- app/services/playvisionSchemas.js
- app/upload-playvision/page.js
- package-lock.json
Added a Playvision Data form with /upload-playvision specifically for playvision data, based on the fields playvision gives after the match, and it uploads it into a seperate collection called playvision in firebase
> Inserting Summary Stats Issue #330
